// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: site/api_site_login.proto

package com.akaxin.proto.site;

public final class ApiSiteLoginProto {
  private ApiSiteLoginProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiSiteLoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiSiteLoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户个人身份公钥
     * </pre>
     *
     * <code>string user_id_pubk = 1;</code>
     */
    java.lang.String getUserIdPubk();
    /**
     * <pre>
     *用户个人身份公钥
     * </pre>
     *
     * <code>string user_id_pubk = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPubkBytes();

    /**
     * <pre>
     *用户设备公钥
     * </pre>
     *
     * <code>string user_device_id_pubk = 2;</code>
     */
    java.lang.String getUserDeviceIdPubk();
    /**
     * <pre>
     *用户设备公钥
     * </pre>
     *
     * <code>string user_device_id_pubk = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserDeviceIdPubkBytes();

    /**
     * <pre>
     *手机号授权token
     * </pre>
     *
     * <code>string phone_token = 3;</code>
     */
    java.lang.String getPhoneToken();
    /**
     * <pre>
     *手机号授权token
     * </pre>
     *
     * <code>string phone_token = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhoneTokenBytes();

    /**
     * <pre>
     *用户设备名称
     * </pre>
     *
     * <code>string user_device_name = 4;</code>
     */
    java.lang.String getUserDeviceName();
    /**
     * <pre>
     *用户设备名称
     * </pre>
     *
     * <code>string user_device_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserDeviceNameBytes();

    /**
     * <pre>
     *akaxin认证token
     * </pre>
     *
     * <code>string user_token = 5;</code>
     */
    java.lang.String getUserToken();
    /**
     * <pre>
     *akaxin认证token
     * </pre>
     *
     * <code>string user_token = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserTokenBytes();

    /**
     * <pre>
     *用户身份公钥签名，证明公钥所属权，需要base64encode。
     * </pre>
     *
     * <code>string user_id_sign_base64 = 6;</code>
     */
    java.lang.String getUserIdSignBase64();
    /**
     * <pre>
     *用户身份公钥签名，证明公钥所属权，需要base64encode。
     * </pre>
     *
     * <code>string user_id_sign_base64 = 6;</code>
     */
    com.google.protobuf.ByteString
        getUserIdSignBase64Bytes();

    /**
     * <pre>
     *使用user_id_prik对用户的user_device_id_pubk签名，证明这个设备是这个用户的。
     * </pre>
     *
     * <code>string user_device_id_sign_base64 = 7;</code>
     */
    java.lang.String getUserDeviceIdSignBase64();
    /**
     * <pre>
     *使用user_id_prik对用户的user_device_id_pubk签名，证明这个设备是这个用户的。
     * </pre>
     *
     * <code>string user_device_id_sign_base64 = 7;</code>
     */
    com.google.protobuf.ByteString
        getUserDeviceIdSignBase64Bytes();
  }
  /**
   * Protobuf type {@code site.ApiSiteLoginRequest}
   */
  public  static final class ApiSiteLoginRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiSiteLoginRequest)
      ApiSiteLoginRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApiSiteLoginRequest.newBuilder() to construct.
    private ApiSiteLoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiSiteLoginRequest() {
      userIdPubk_ = "";
      userDeviceIdPubk_ = "";
      phoneToken_ = "";
      userDeviceName_ = "";
      userToken_ = "";
      userIdSignBase64_ = "";
      userDeviceIdSignBase64_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ApiSiteLoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPubk_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userDeviceIdPubk_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneToken_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userDeviceName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              userToken_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdSignBase64_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              userDeviceIdSignBase64_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.site.ApiSiteLoginProto.internal_static_site_ApiSiteLoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.site.ApiSiteLoginProto.internal_static_site_ApiSiteLoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest.class, com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest.Builder.class);
    }

    public static final int USER_ID_PUBK_FIELD_NUMBER = 1;
    private volatile java.lang.Object userIdPubk_;
    /**
     * <pre>
     *用户个人身份公钥
     * </pre>
     *
     * <code>string user_id_pubk = 1;</code>
     */
    public java.lang.String getUserIdPubk() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPubk_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户个人身份公钥
     * </pre>
     *
     * <code>string user_id_pubk = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPubkBytes() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_DEVICE_ID_PUBK_FIELD_NUMBER = 2;
    private volatile java.lang.Object userDeviceIdPubk_;
    /**
     * <pre>
     *用户设备公钥
     * </pre>
     *
     * <code>string user_device_id_pubk = 2;</code>
     */
    public java.lang.String getUserDeviceIdPubk() {
      java.lang.Object ref = userDeviceIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userDeviceIdPubk_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户设备公钥
     * </pre>
     *
     * <code>string user_device_id_pubk = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserDeviceIdPubkBytes() {
      java.lang.Object ref = userDeviceIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userDeviceIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_TOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object phoneToken_;
    /**
     * <pre>
     *手机号授权token
     * </pre>
     *
     * <code>string phone_token = 3;</code>
     */
    public java.lang.String getPhoneToken() {
      java.lang.Object ref = phoneToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *手机号授权token
     * </pre>
     *
     * <code>string phone_token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneTokenBytes() {
      java.lang.Object ref = phoneToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_DEVICE_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object userDeviceName_;
    /**
     * <pre>
     *用户设备名称
     * </pre>
     *
     * <code>string user_device_name = 4;</code>
     */
    public java.lang.String getUserDeviceName() {
      java.lang.Object ref = userDeviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userDeviceName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户设备名称
     * </pre>
     *
     * <code>string user_device_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserDeviceNameBytes() {
      java.lang.Object ref = userDeviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userDeviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_TOKEN_FIELD_NUMBER = 5;
    private volatile java.lang.Object userToken_;
    /**
     * <pre>
     *akaxin认证token
     * </pre>
     *
     * <code>string user_token = 5;</code>
     */
    public java.lang.String getUserToken() {
      java.lang.Object ref = userToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *akaxin认证token
     * </pre>
     *
     * <code>string user_token = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserTokenBytes() {
      java.lang.Object ref = userToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_SIGN_BASE64_FIELD_NUMBER = 6;
    private volatile java.lang.Object userIdSignBase64_;
    /**
     * <pre>
     *用户身份公钥签名，证明公钥所属权，需要base64encode。
     * </pre>
     *
     * <code>string user_id_sign_base64 = 6;</code>
     */
    public java.lang.String getUserIdSignBase64() {
      java.lang.Object ref = userIdSignBase64_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdSignBase64_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户身份公钥签名，证明公钥所属权，需要base64encode。
     * </pre>
     *
     * <code>string user_id_sign_base64 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdSignBase64Bytes() {
      java.lang.Object ref = userIdSignBase64_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdSignBase64_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_DEVICE_ID_SIGN_BASE64_FIELD_NUMBER = 7;
    private volatile java.lang.Object userDeviceIdSignBase64_;
    /**
     * <pre>
     *使用user_id_prik对用户的user_device_id_pubk签名，证明这个设备是这个用户的。
     * </pre>
     *
     * <code>string user_device_id_sign_base64 = 7;</code>
     */
    public java.lang.String getUserDeviceIdSignBase64() {
      java.lang.Object ref = userDeviceIdSignBase64_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userDeviceIdSignBase64_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *使用user_id_prik对用户的user_device_id_pubk签名，证明这个设备是这个用户的。
     * </pre>
     *
     * <code>string user_device_id_sign_base64 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUserDeviceIdSignBase64Bytes() {
      java.lang.Object ref = userDeviceIdSignBase64_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userDeviceIdSignBase64_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userIdPubk_);
      }
      if (!getUserDeviceIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userDeviceIdPubk_);
      }
      if (!getPhoneTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phoneToken_);
      }
      if (!getUserDeviceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userDeviceName_);
      }
      if (!getUserTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userToken_);
      }
      if (!getUserIdSignBase64Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userIdSignBase64_);
      }
      if (!getUserDeviceIdSignBase64Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, userDeviceIdSignBase64_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userIdPubk_);
      }
      if (!getUserDeviceIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userDeviceIdPubk_);
      }
      if (!getPhoneTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phoneToken_);
      }
      if (!getUserDeviceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userDeviceName_);
      }
      if (!getUserTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userToken_);
      }
      if (!getUserIdSignBase64Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userIdSignBase64_);
      }
      if (!getUserDeviceIdSignBase64Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, userDeviceIdSignBase64_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest)) {
        return super.equals(obj);
      }
      com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest other = (com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest) obj;

      boolean result = true;
      result = result && getUserIdPubk()
          .equals(other.getUserIdPubk());
      result = result && getUserDeviceIdPubk()
          .equals(other.getUserDeviceIdPubk());
      result = result && getPhoneToken()
          .equals(other.getPhoneToken());
      result = result && getUserDeviceName()
          .equals(other.getUserDeviceName());
      result = result && getUserToken()
          .equals(other.getUserToken());
      result = result && getUserIdSignBase64()
          .equals(other.getUserIdSignBase64());
      result = result && getUserDeviceIdSignBase64()
          .equals(other.getUserDeviceIdSignBase64());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPubk().hashCode();
      hash = (37 * hash) + USER_DEVICE_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserDeviceIdPubk().hashCode();
      hash = (37 * hash) + PHONE_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneToken().hashCode();
      hash = (37 * hash) + USER_DEVICE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserDeviceName().hashCode();
      hash = (37 * hash) + USER_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getUserToken().hashCode();
      hash = (37 * hash) + USER_ID_SIGN_BASE64_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdSignBase64().hashCode();
      hash = (37 * hash) + USER_DEVICE_ID_SIGN_BASE64_FIELD_NUMBER;
      hash = (53 * hash) + getUserDeviceIdSignBase64().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiSiteLoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiSiteLoginRequest)
        com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.site.ApiSiteLoginProto.internal_static_site_ApiSiteLoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.site.ApiSiteLoginProto.internal_static_site_ApiSiteLoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest.class, com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest.Builder.class);
      }

      // Construct using com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userIdPubk_ = "";

        userDeviceIdPubk_ = "";

        phoneToken_ = "";

        userDeviceName_ = "";

        userToken_ = "";

        userIdSignBase64_ = "";

        userDeviceIdSignBase64_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.site.ApiSiteLoginProto.internal_static_site_ApiSiteLoginRequest_descriptor;
      }

      public com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest getDefaultInstanceForType() {
        return com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest.getDefaultInstance();
      }

      public com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest build() {
        com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest buildPartial() {
        com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest result = new com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest(this);
        result.userIdPubk_ = userIdPubk_;
        result.userDeviceIdPubk_ = userDeviceIdPubk_;
        result.phoneToken_ = phoneToken_;
        result.userDeviceName_ = userDeviceName_;
        result.userToken_ = userToken_;
        result.userIdSignBase64_ = userIdSignBase64_;
        result.userDeviceIdSignBase64_ = userDeviceIdSignBase64_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest) {
          return mergeFrom((com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest other) {
        if (other == com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest.getDefaultInstance()) return this;
        if (!other.getUserIdPubk().isEmpty()) {
          userIdPubk_ = other.userIdPubk_;
          onChanged();
        }
        if (!other.getUserDeviceIdPubk().isEmpty()) {
          userDeviceIdPubk_ = other.userDeviceIdPubk_;
          onChanged();
        }
        if (!other.getPhoneToken().isEmpty()) {
          phoneToken_ = other.phoneToken_;
          onChanged();
        }
        if (!other.getUserDeviceName().isEmpty()) {
          userDeviceName_ = other.userDeviceName_;
          onChanged();
        }
        if (!other.getUserToken().isEmpty()) {
          userToken_ = other.userToken_;
          onChanged();
        }
        if (!other.getUserIdSignBase64().isEmpty()) {
          userIdSignBase64_ = other.userIdSignBase64_;
          onChanged();
        }
        if (!other.getUserDeviceIdSignBase64().isEmpty()) {
          userDeviceIdSignBase64_ = other.userDeviceIdSignBase64_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userIdPubk_ = "";
      /**
       * <pre>
       *用户个人身份公钥
       * </pre>
       *
       * <code>string user_id_pubk = 1;</code>
       */
      public java.lang.String getUserIdPubk() {
        java.lang.Object ref = userIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户个人身份公钥
       * </pre>
       *
       * <code>string user_id_pubk = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPubkBytes() {
        java.lang.Object ref = userIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户个人身份公钥
       * </pre>
       *
       * <code>string user_id_pubk = 1;</code>
       */
      public Builder setUserIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户个人身份公钥
       * </pre>
       *
       * <code>string user_id_pubk = 1;</code>
       */
      public Builder clearUserIdPubk() {
        
        userIdPubk_ = getDefaultInstance().getUserIdPubk();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户个人身份公钥
       * </pre>
       *
       * <code>string user_id_pubk = 1;</code>
       */
      public Builder setUserIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userDeviceIdPubk_ = "";
      /**
       * <pre>
       *用户设备公钥
       * </pre>
       *
       * <code>string user_device_id_pubk = 2;</code>
       */
      public java.lang.String getUserDeviceIdPubk() {
        java.lang.Object ref = userDeviceIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userDeviceIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户设备公钥
       * </pre>
       *
       * <code>string user_device_id_pubk = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserDeviceIdPubkBytes() {
        java.lang.Object ref = userDeviceIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userDeviceIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户设备公钥
       * </pre>
       *
       * <code>string user_device_id_pubk = 2;</code>
       */
      public Builder setUserDeviceIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userDeviceIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户设备公钥
       * </pre>
       *
       * <code>string user_device_id_pubk = 2;</code>
       */
      public Builder clearUserDeviceIdPubk() {
        
        userDeviceIdPubk_ = getDefaultInstance().getUserDeviceIdPubk();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户设备公钥
       * </pre>
       *
       * <code>string user_device_id_pubk = 2;</code>
       */
      public Builder setUserDeviceIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userDeviceIdPubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phoneToken_ = "";
      /**
       * <pre>
       *手机号授权token
       * </pre>
       *
       * <code>string phone_token = 3;</code>
       */
      public java.lang.String getPhoneToken() {
        java.lang.Object ref = phoneToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *手机号授权token
       * </pre>
       *
       * <code>string phone_token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneTokenBytes() {
        java.lang.Object ref = phoneToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *手机号授权token
       * </pre>
       *
       * <code>string phone_token = 3;</code>
       */
      public Builder setPhoneToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号授权token
       * </pre>
       *
       * <code>string phone_token = 3;</code>
       */
      public Builder clearPhoneToken() {
        
        phoneToken_ = getDefaultInstance().getPhoneToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号授权token
       * </pre>
       *
       * <code>string phone_token = 3;</code>
       */
      public Builder setPhoneTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userDeviceName_ = "";
      /**
       * <pre>
       *用户设备名称
       * </pre>
       *
       * <code>string user_device_name = 4;</code>
       */
      public java.lang.String getUserDeviceName() {
        java.lang.Object ref = userDeviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userDeviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户设备名称
       * </pre>
       *
       * <code>string user_device_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserDeviceNameBytes() {
        java.lang.Object ref = userDeviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userDeviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户设备名称
       * </pre>
       *
       * <code>string user_device_name = 4;</code>
       */
      public Builder setUserDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userDeviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户设备名称
       * </pre>
       *
       * <code>string user_device_name = 4;</code>
       */
      public Builder clearUserDeviceName() {
        
        userDeviceName_ = getDefaultInstance().getUserDeviceName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户设备名称
       * </pre>
       *
       * <code>string user_device_name = 4;</code>
       */
      public Builder setUserDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userDeviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userToken_ = "";
      /**
       * <pre>
       *akaxin认证token
       * </pre>
       *
       * <code>string user_token = 5;</code>
       */
      public java.lang.String getUserToken() {
        java.lang.Object ref = userToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *akaxin认证token
       * </pre>
       *
       * <code>string user_token = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserTokenBytes() {
        java.lang.Object ref = userToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *akaxin认证token
       * </pre>
       *
       * <code>string user_token = 5;</code>
       */
      public Builder setUserToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *akaxin认证token
       * </pre>
       *
       * <code>string user_token = 5;</code>
       */
      public Builder clearUserToken() {
        
        userToken_ = getDefaultInstance().getUserToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *akaxin认证token
       * </pre>
       *
       * <code>string user_token = 5;</code>
       */
      public Builder setUserTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userIdSignBase64_ = "";
      /**
       * <pre>
       *用户身份公钥签名，证明公钥所属权，需要base64encode。
       * </pre>
       *
       * <code>string user_id_sign_base64 = 6;</code>
       */
      public java.lang.String getUserIdSignBase64() {
        java.lang.Object ref = userIdSignBase64_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdSignBase64_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户身份公钥签名，证明公钥所属权，需要base64encode。
       * </pre>
       *
       * <code>string user_id_sign_base64 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdSignBase64Bytes() {
        java.lang.Object ref = userIdSignBase64_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdSignBase64_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户身份公钥签名，证明公钥所属权，需要base64encode。
       * </pre>
       *
       * <code>string user_id_sign_base64 = 6;</code>
       */
      public Builder setUserIdSignBase64(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdSignBase64_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥签名，证明公钥所属权，需要base64encode。
       * </pre>
       *
       * <code>string user_id_sign_base64 = 6;</code>
       */
      public Builder clearUserIdSignBase64() {
        
        userIdSignBase64_ = getDefaultInstance().getUserIdSignBase64();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户身份公钥签名，证明公钥所属权，需要base64encode。
       * </pre>
       *
       * <code>string user_id_sign_base64 = 6;</code>
       */
      public Builder setUserIdSignBase64Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdSignBase64_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userDeviceIdSignBase64_ = "";
      /**
       * <pre>
       *使用user_id_prik对用户的user_device_id_pubk签名，证明这个设备是这个用户的。
       * </pre>
       *
       * <code>string user_device_id_sign_base64 = 7;</code>
       */
      public java.lang.String getUserDeviceIdSignBase64() {
        java.lang.Object ref = userDeviceIdSignBase64_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userDeviceIdSignBase64_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *使用user_id_prik对用户的user_device_id_pubk签名，证明这个设备是这个用户的。
       * </pre>
       *
       * <code>string user_device_id_sign_base64 = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUserDeviceIdSignBase64Bytes() {
        java.lang.Object ref = userDeviceIdSignBase64_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userDeviceIdSignBase64_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *使用user_id_prik对用户的user_device_id_pubk签名，证明这个设备是这个用户的。
       * </pre>
       *
       * <code>string user_device_id_sign_base64 = 7;</code>
       */
      public Builder setUserDeviceIdSignBase64(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userDeviceIdSignBase64_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *使用user_id_prik对用户的user_device_id_pubk签名，证明这个设备是这个用户的。
       * </pre>
       *
       * <code>string user_device_id_sign_base64 = 7;</code>
       */
      public Builder clearUserDeviceIdSignBase64() {
        
        userDeviceIdSignBase64_ = getDefaultInstance().getUserDeviceIdSignBase64();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *使用user_id_prik对用户的user_device_id_pubk签名，证明这个设备是这个用户的。
       * </pre>
       *
       * <code>string user_device_id_sign_base64 = 7;</code>
       */
      public Builder setUserDeviceIdSignBase64Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userDeviceIdSignBase64_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:site.ApiSiteLoginRequest)
    }

    // @@protoc_insertion_point(class_scope:site.ApiSiteLoginRequest)
    private static final com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest();
    }

    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiSiteLoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiSiteLoginRequest>() {
      public ApiSiteLoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApiSiteLoginRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiSiteLoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiSiteLoginRequest> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiSiteLoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiSiteLoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户个人sessionId
     * </pre>
     *
     * <code>string user_session_id = 1;</code>
     */
    java.lang.String getUserSessionId();
    /**
     * <pre>
     *用户个人sessionId
     * </pre>
     *
     * <code>string user_session_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserSessionIdBytes();

    /**
     * <pre>
     *返回站点用户ID
     * </pre>
     *
     * <code>string site_user_id = 2;</code>
     */
    java.lang.String getSiteUserId();
    /**
     * <pre>
     *返回站点用户ID
     * </pre>
     *
     * <code>string site_user_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getSiteUserIdBytes();

    /**
     * <pre>
     *返回站点的设备ID
     * </pre>
     *
     * <code>string site_device_id = 3;</code>
     */
    java.lang.String getSiteDeviceId();
    /**
     * <pre>
     *返回站点的设备ID
     * </pre>
     *
     * <code>string site_device_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getSiteDeviceIdBytes();
  }
  /**
   * Protobuf type {@code site.ApiSiteLoginResponse}
   */
  public  static final class ApiSiteLoginResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiSiteLoginResponse)
      ApiSiteLoginResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApiSiteLoginResponse.newBuilder() to construct.
    private ApiSiteLoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiSiteLoginResponse() {
      userSessionId_ = "";
      siteUserId_ = "";
      siteDeviceId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ApiSiteLoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userSessionId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              siteUserId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              siteDeviceId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akaxin.proto.site.ApiSiteLoginProto.internal_static_site_ApiSiteLoginResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akaxin.proto.site.ApiSiteLoginProto.internal_static_site_ApiSiteLoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse.class, com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse.Builder.class);
    }

    public static final int USER_SESSION_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userSessionId_;
    /**
     * <pre>
     *用户个人sessionId
     * </pre>
     *
     * <code>string user_session_id = 1;</code>
     */
    public java.lang.String getUserSessionId() {
      java.lang.Object ref = userSessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userSessionId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户个人sessionId
     * </pre>
     *
     * <code>string user_session_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserSessionIdBytes() {
      java.lang.Object ref = userSessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userSessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITE_USER_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object siteUserId_;
    /**
     * <pre>
     *返回站点用户ID
     * </pre>
     *
     * <code>string site_user_id = 2;</code>
     */
    public java.lang.String getSiteUserId() {
      java.lang.Object ref = siteUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteUserId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *返回站点用户ID
     * </pre>
     *
     * <code>string site_user_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSiteUserIdBytes() {
      java.lang.Object ref = siteUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITE_DEVICE_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object siteDeviceId_;
    /**
     * <pre>
     *返回站点的设备ID
     * </pre>
     *
     * <code>string site_device_id = 3;</code>
     */
    public java.lang.String getSiteDeviceId() {
      java.lang.Object ref = siteDeviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteDeviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *返回站点的设备ID
     * </pre>
     *
     * <code>string site_device_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSiteDeviceIdBytes() {
      java.lang.Object ref = siteDeviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteDeviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userSessionId_);
      }
      if (!getSiteUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, siteUserId_);
      }
      if (!getSiteDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, siteDeviceId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userSessionId_);
      }
      if (!getSiteUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, siteUserId_);
      }
      if (!getSiteDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, siteDeviceId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse)) {
        return super.equals(obj);
      }
      com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse other = (com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse) obj;

      boolean result = true;
      result = result && getUserSessionId()
          .equals(other.getUserSessionId());
      result = result && getSiteUserId()
          .equals(other.getSiteUserId());
      result = result && getSiteDeviceId()
          .equals(other.getSiteDeviceId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserSessionId().hashCode();
      hash = (37 * hash) + SITE_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSiteUserId().hashCode();
      hash = (37 * hash) + SITE_DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSiteDeviceId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiSiteLoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiSiteLoginResponse)
        com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akaxin.proto.site.ApiSiteLoginProto.internal_static_site_ApiSiteLoginResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akaxin.proto.site.ApiSiteLoginProto.internal_static_site_ApiSiteLoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse.class, com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse.Builder.class);
      }

      // Construct using com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userSessionId_ = "";

        siteUserId_ = "";

        siteDeviceId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akaxin.proto.site.ApiSiteLoginProto.internal_static_site_ApiSiteLoginResponse_descriptor;
      }

      public com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse getDefaultInstanceForType() {
        return com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse.getDefaultInstance();
      }

      public com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse build() {
        com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse buildPartial() {
        com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse result = new com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse(this);
        result.userSessionId_ = userSessionId_;
        result.siteUserId_ = siteUserId_;
        result.siteDeviceId_ = siteDeviceId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse) {
          return mergeFrom((com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse other) {
        if (other == com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse.getDefaultInstance()) return this;
        if (!other.getUserSessionId().isEmpty()) {
          userSessionId_ = other.userSessionId_;
          onChanged();
        }
        if (!other.getSiteUserId().isEmpty()) {
          siteUserId_ = other.siteUserId_;
          onChanged();
        }
        if (!other.getSiteDeviceId().isEmpty()) {
          siteDeviceId_ = other.siteDeviceId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userSessionId_ = "";
      /**
       * <pre>
       *用户个人sessionId
       * </pre>
       *
       * <code>string user_session_id = 1;</code>
       */
      public java.lang.String getUserSessionId() {
        java.lang.Object ref = userSessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userSessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户个人sessionId
       * </pre>
       *
       * <code>string user_session_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserSessionIdBytes() {
        java.lang.Object ref = userSessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userSessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户个人sessionId
       * </pre>
       *
       * <code>string user_session_id = 1;</code>
       */
      public Builder setUserSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userSessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户个人sessionId
       * </pre>
       *
       * <code>string user_session_id = 1;</code>
       */
      public Builder clearUserSessionId() {
        
        userSessionId_ = getDefaultInstance().getUserSessionId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户个人sessionId
       * </pre>
       *
       * <code>string user_session_id = 1;</code>
       */
      public Builder setUserSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userSessionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object siteUserId_ = "";
      /**
       * <pre>
       *返回站点用户ID
       * </pre>
       *
       * <code>string site_user_id = 2;</code>
       */
      public java.lang.String getSiteUserId() {
        java.lang.Object ref = siteUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *返回站点用户ID
       * </pre>
       *
       * <code>string site_user_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSiteUserIdBytes() {
        java.lang.Object ref = siteUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *返回站点用户ID
       * </pre>
       *
       * <code>string site_user_id = 2;</code>
       */
      public Builder setSiteUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回站点用户ID
       * </pre>
       *
       * <code>string site_user_id = 2;</code>
       */
      public Builder clearSiteUserId() {
        
        siteUserId_ = getDefaultInstance().getSiteUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回站点用户ID
       * </pre>
       *
       * <code>string site_user_id = 2;</code>
       */
      public Builder setSiteUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteUserId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object siteDeviceId_ = "";
      /**
       * <pre>
       *返回站点的设备ID
       * </pre>
       *
       * <code>string site_device_id = 3;</code>
       */
      public java.lang.String getSiteDeviceId() {
        java.lang.Object ref = siteDeviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteDeviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *返回站点的设备ID
       * </pre>
       *
       * <code>string site_device_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSiteDeviceIdBytes() {
        java.lang.Object ref = siteDeviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteDeviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *返回站点的设备ID
       * </pre>
       *
       * <code>string site_device_id = 3;</code>
       */
      public Builder setSiteDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteDeviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回站点的设备ID
       * </pre>
       *
       * <code>string site_device_id = 3;</code>
       */
      public Builder clearSiteDeviceId() {
        
        siteDeviceId_ = getDefaultInstance().getSiteDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回站点的设备ID
       * </pre>
       *
       * <code>string site_device_id = 3;</code>
       */
      public Builder setSiteDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteDeviceId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:site.ApiSiteLoginResponse)
    }

    // @@protoc_insertion_point(class_scope:site.ApiSiteLoginResponse)
    private static final com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse();
    }

    public static com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiSiteLoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiSiteLoginResponse>() {
      public ApiSiteLoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApiSiteLoginResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiSiteLoginResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiSiteLoginResponse> getParserForType() {
      return PARSER;
    }

    public com.akaxin.proto.site.ApiSiteLoginProto.ApiSiteLoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiSiteLoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiSiteLoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiSiteLoginResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiSiteLoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031site/api_site_login.proto\022\004site\"\314\001\n\023Ap" +
      "iSiteLoginRequest\022\024\n\014user_id_pubk\030\001 \001(\t\022" +
      "\033\n\023user_device_id_pubk\030\002 \001(\t\022\023\n\013phone_to" +
      "ken\030\003 \001(\t\022\030\n\020user_device_name\030\004 \001(\t\022\022\n\nu" +
      "ser_token\030\005 \001(\t\022\033\n\023user_id_sign_base64\030\006" +
      " \001(\t\022\"\n\032user_device_id_sign_base64\030\007 \001(\t" +
      "\"]\n\024ApiSiteLoginResponse\022\027\n\017user_session" +
      "_id\030\001 \001(\t\022\024\n\014site_user_id\030\002 \001(\t\022\026\n\016site_" +
      "device_id\030\003 \001(\t2U\n\023ApiSiteLoginService\022>" +
      "\n\005login\022\031.site.ApiSiteLoginRequest\032\032.sit" +
      "e.ApiSiteLoginResponseB*\n\025com.akaxin.pro" +
      "to.siteB\021ApiSiteLoginProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_site_ApiSiteLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_ApiSiteLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiSiteLoginRequest_descriptor,
        new java.lang.String[] { "UserIdPubk", "UserDeviceIdPubk", "PhoneToken", "UserDeviceName", "UserToken", "UserIdSignBase64", "UserDeviceIdSignBase64", });
    internal_static_site_ApiSiteLoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_ApiSiteLoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiSiteLoginResponse_descriptor,
        new java.lang.String[] { "UserSessionId", "SiteUserId", "SiteDeviceId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
